#!/bin/bash
set -eu
source "$(cd "$(dirname "$0")"; pwd)/config.sh"

# dependencies
case "$1" in
'windows')
    pacman -S --noconfirm mingw-w64-x86_64-gcc make git
    pacman -S --noconfirm autoconf pkg-config texinfo
    pacman -S --noconfirm mingw-w64-x86_64-gnutls mingw-w64-x86_64-jansson
    ;;
'linux')
    sudo -E apt install -y build-essential
    sudo -E apt install -y autoconf pkg-config texinfo
    sudo -E apt install -y libncurses-dev libgnutls${GNUTLS_VERSION}-dev libjansson-dev
    ;;
esac

# create working dir
mkdir -p "$ROOT/tmp"
cd "$ROOT/tmp"

# retrieve emacs source
if [ ! -e "./emacs-${VERSION}.tar.gz" ]; then
    wget "https://github.com/emacs-mirror/emacs/archive/refs/tags/emacs-${VERSION}.tar.gz"
fi

# extract
if [ ! -d "./emacs-emacs-${VERSION}" ]; then
    tar zxf "emacs-${VERSION}.tar.gz"
fi

# build
cd "./emacs-emacs-${VERSION}"
./autogen.sh

options='  --disable-build-details'
options+=' --without-all'
options+=' --without-pop'
options+=' --with-xml2'
options+=' --with-json'
options+=' --with-gnutls'
options+=' --with-zlib'
options+=' --with-modules'
options+=' --with-threads'
options+=' --with-file-notification=yes'

case "$1" in
'windows')
    # CFLAGS='-O2 -march=x86-64 -mtune=generic -static -s -g0'
    CFLAGS='-O2 -march=x86-64 -static'
    ./configure $options --prefix="$INSTALL_DIR" --with-toolkit-scroll-bars
    make bootstrap -j $(nproc)
    make install-strip
    cp /mingw64/bin/*.dll "$INSTALL_DIR/bin/"
    ;;
'linux')
    CFLAGS='-O2 -march=x86-64'
    ./configure $options --prefix="$INSTALL_DIR" --without-x
    make -j $(nproc)
    sudo make install
    sudo chown -R $USER "$INSTALL_DIR"
    ;;
esac

