name: TEST

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
      - run: touch /opt/aaa
      - run: dir C:\mingw64\
        shell: cmd
      - run: dir C:\mingw64\opt
        shell: cmd
