name: TEST

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            zip
      - run: type zip
      - run: type tar
