name: Build Emacs

on:
  push:
    tags:
      - "v[0-9]+.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./build
      - run: ./appimage
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: out/
