name: 'emacs build'

on:
  workflow_dispatch:
  push:
    tags:
      'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./build
      - run: ./appimage
      - run: ls out
