name: Build Emacs

on:
  push:
    tags:
      - "v[0-9]+.*"
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./build
      - run: ./appimage
      - uses: actions/upload-artifact@v3
        with:
          name: output_linux
          path: out/

  publish:
    runs-on: ubuntu-latest
    needs: [linux]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: output_linux
          
      - run: ls -lh

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            emacs-28.1-x86_64.tar.gz
            emacs-x86_64.AppImage
